---
title: "Osteosarcoma chemoresistance: Yogesh"
output: github_document
---

```{r setup, include=FALSE}
library(rrrSingleCellUtils)
library(Seurat)
library(ggrepel)
library(tidyverse)
library(stringr)
library(harmony)
library(cowplot)

set.seed(444)

```

```{r}
set.seed(75454)
sample_details <- read_tsv("sample_detail.txt", show_col_types = FALSE)

sample_details <- dplyr::filter(sample_details,
                                cellline == "F420")


obj <- parallel::mclapply(seq_len(nrow(sample_details)), function(i) {
    sample_name <- sample_details$sample_name[i]
    sample_path <- sample_details$sample_path[i]
    species <- sample_details$species[i]
    tumor_type <- sample_details$tumor_type[i]
    sp_pattern <- sample_details$sp_pattern[i]
    organism <- sample_details$organism[i]
    data_details <- sample_details$data_details[i]
    ours_path <- "/gpfs0/home2/gdrobertslab/lab/Counts_2/"

    path_h5 <- paste0(path_10x = ours_path,
                           sample_path,
                           "/filtered_feature_bc_matrix.h5")

    sobj <- rrrSingleCellUtils::tenx_load_qc(h5_file = path_h5,
                                            violin_plot = FALSE,
                                            min_cells = 1,
                                            min_features = 1)
    sobj <- sobj %>%
        process_seurat()
    sobj$sample_name <- sample_details$sample_name[i]
    sobj$tumor_type <- sample_details$tumor_type[i]
    sobj$data_type <- sample_details$data_type[i]
    sobj$organism <- sample_details$organism[i]
    sobj$species <- sample_details$species[i]
    sobj$data_details <- sample_details$data_details[i]
    qs::qsave(sobj, str_c("output/seurat_objects/single_sobj/",
                          organism, "/",
                          sample_name, ".qs"))
    return(0)
}, mc.cores = 10)






# individual QC numbers
sobj <- qs::qread("output/seurat_objects/single_sobj/mouse/S0272.qs") #nolint

# Cutoff and cleaning
try_cutoff <- tribble(~feature,     ~min_val, ~max_val,
                      "nCount_RNA", 0,        30000,
                      "percent.mt", 0,        15)

features <- c("nFeature_RNA", "nCount_RNA", "percent.mt")    #nolint

# visualize the possible cutoff and adjust accordingly
feature_hist(sobject = sobj,
             features = features,                         # nolint
             cutoff_table = try_cutoff)


#quality control and downsampling and saving the merged sobj
# what <- parallel::mclapply(unique(sample_details$organism), function(item) {
#     tmp_df <- subset(sample_details, subset = (organism == item))
temp_list <- list()
for (i in seq_len(nrow(sample_details))) {
    sample_name <- sample_details$sample_name[i]
    sample_path <- sample_details$sample_path[i]
    species <- sample_details$species[i]
    tumor_type <- sample_details$tumor_type[i]
    #sp_pattern <- sample_details$sp_pattern[i]
    organism <- sample_details$organism[i]
    data_details <- sample_details$data_details[i]
    sobj <- qs::qread(str_c("output/seurat_objects/single_sobj/",
                            organism, "/",
                            sample_name, ".qs")) %>%
        subset(nCount_RNA > 600 &
              nCount_RNA < sample_details$ncount_max[i] &
              percent.mt < sample_details$mt_percent[i])
    temp_list[[sample_name]] <- sobj
    # temp_list[[sample_name]] <-
    #         subset(x = temp_list[[sample_name]],
    #         cells = sample(Cells(temp_list[[sample_name]]),
    #                 min(5000, length(Cells(temp_list[[sample_name]])))))
}
merged_sobj <- merge(x = temp_list[[1]],
                            y = temp_list[2:length(temp_list)],
                            add.cell.id = names(temp_list)) %>%
                process_seurat() %>%
                JoinLayers()
#DimPlot(merged_sobj, group.by = "sample_name")
qs::qsave(merged_sobj, str_c("output/seurat_objects/comb_sobjs.qs"))

run_harmony <- RunHarmony(object = merged_sobj,
                            group.by.vars = "sample_name")   #need to include data_type as another batch #nolint

run_harmony <- process_seurat(sobject = run_harmony,
                                reduction = "harmony")
DimPlot(run_harmony,
        group.by = c("seurat_clusters", "sample_name"),
        cols = c(plot_cols, sample(rainbow(1000))),
        shuffle = TRUE)


qs::qsave(run_harmony, str_c("output/seurat_objects/harmony_sobjs.qs"))

FeaturePlot(run_harmony, features = c("nCount_RNA", "percent.mt"), cols = c("blue", "red"))
FeaturePlot(run_harmony, features = c("Col1a1", "Col1a2", "Satb2", "Col3a1"))


```


```{r}
human_sobj <- qs::qread("output/seurat_objects/harmony_sobjs.qs")

annotated <- annotate(sobj = human_sobj,
                    species = "mouse",
                    aggr_ref = TRUE)

DimPlot(annotated,
        group.by = c("sample_name", "annotations", "seurat_clusters", "data_details"),
        label = TRUE,
        cols = c(plot_cols, sample(rainbow(1000))),
        shuffle = TRUE)

table(annotated$annotations)

Idents(annotated) <- annotated$annotations

cancer <- subset(annotated,
                idents = c("Fibroblasts")) %>%
    process_seurat() %>%
    RunHarmony(group.by.vars = "sample_name") %>%
    process_seurat(reduction = "harmony")

DimPlot(cancer,
        group.by = c("sample_name", "annotations", "seurat_clusters", "data_details"),
        label = TRUE,
        cols = c(plot_cols, sample(rainbow(1000))),
        shuffle = TRUE)

Idents(cancer) <- cancer$data_details

degs_result <- cancer %>%
    Seurat::FindMarkers(ident.1 = "Anakinra",
                        ident.2 = "Control")

FeaturePlot(cancer, features = c("Col1a1", "Col1a2", "Satb2", "Col3a1"))

degs_result <- degs_result %>%
    arrange(desc(avg_log2FC))

degs_result$symbol = rownames(degs_result)

theme_set(theme_classic(base_size = 20) +
        theme(axis.title.y = element_text(margin = margin(0, 20, 0, 0),
                                            size = 10,
                                            color = "black",
                                            face = "bold"),
                axis.title.x = element_text(hjust = 0.5,
                                            margin = margin(20, 0, 0, 0),
                                            size = 10,
                                            color = "black",
                                            face = "bold"),
                plot.title = element_text(hjust = 0.5,
                                        size = 10,
                                        face = "bold"),
                legend.text = element_text(size = 8,
                                            face = "bold")))


logfc_cutoff <- 0.6

degs_result$diffexpressed <- "Not Significant"
degs_result$diffexpressed[degs_result$avg_log2FC > logfc_cutoff & degs_result$p_val_adj < 0.05] <- "Upregulated"
degs_result$diffexpressed[degs_result$avg_log2FC < -1 * logfc_cutoff & degs_result$p_val_adj < 0.05] <- "Downregulated"

volc_plot <- ggplot(data=degs_result,
                        aes(x=avg_log2FC,
                            y=-log10(p_val),
                            color = diffexpressed)) + 
    geom_vline(xintercept = c(-1 * logfc_cutoff, logfc_cutoff),
               col = "gray",
               linetype = "dashed") + 
    geom_hline(yintercept = c(0.05),
              col = "gray",
              linetype = "dashed") +
    geom_point(size = 2) +
    scale_color_manual(values = c(plot_cols[1], "grey", plot_cols[2]),
                        name = "") +
    geom_text_repel(aes(label = symbol),
                        # force_pull = 7,
                        # force = 7,
                        size = 3) +
    ggtitle(str_c("")) 

volc_plot

sub <- subset(cancer, idents = c("Anakinra", "Control"))

list_gene <- degs_result %>% head(5) %>% rownames()

VlnPlot(sub, features = list_gene, group.by = "data_details")

Average_exp <- AverageExpression(sub, group.by = "data_details") %>% 
    as.data.frame() %>%
    rownames_to_column(var = "gene") %>%
    arrange(desc(RNA.Anakinra))

gsea_ref <- msigdbr::msigdbr(species = "Homo sapiens",
                             category = "C2",
                             subcategory = "CP:KEGG") %>%
    split(x = .$gene_symbol, f = .$gs_name)

gsea_input <- as.vector(degs_result$avg_log2FC)
names(gsea_input) <- rownames(degs_result)

gsea_output <- fgsea::fgseaMultilevel(gsea_ref,
                                         gsea_input,
                                         minSize = 10,
                                         maxSize = 500,
                                         nPerm = 1000)

gsea_output <- gsea_output %>%
            dplyr::arrange(desc(NES)) %>%
            filter(padj < 0.05) %>% 
            mutate(pathway = stringr::str_replace_all(pathway, "_", " "))


two_way_dotplot <- function(data, x_col = "z_score") {
    lab4plot <-
        tibble(y = c(-2.5, 2.5),
               x = c(0.2, 0.2),
               label = c("Downregulated", "Upregulated"))

    plot_name <-
        ggplot() +
        geom_point(data = data,
                 aes(x = -1 * order,
                     y = get(x_col),
                     color = -log10(padj),
                     size = size),
                 stat = "identity",
                 alpha = 0.8) +
        coord_flip() +
        # geom_hline(yintercept = 0,
        #             color = "black",
        #             linewidth = 0.5) +
        geom_text(data = data,                #text for pathways names
                    aes(x = -1 * order,
                        y = get(x_col) + (y_pos *5),
                        hjust = justify_y,
                        label = pathway),
                        size = 2,
                        fontface = "bold") +
        geom_text(data = lab4plot,    #text for upregulated/downregulated
                  aes(x = x,
                      y = y,
                      label = label),
                  fontface = "bold",
                  size = 2.5) +
        scale_fill_manual(values = plot_cols,
                          name = paste0(x_col, " > 0")) +
        theme(strip.background = element_rect(color = "white",
                                              fill = "white"),
              #legend.position = "none",
              panel.grid.major = element_blank(),
              panel.grid.minor = element_blank(),
              panel.border = element_blank(),
              axis.line.x = element_line(color = "black"),
              axis.line.y = element_blank(),
              axis.title.x = element_text(size = 7),
              axis.ticks.y = element_blank(),
              plot.title = element_text(size = 7, face = "bold"),    #title of the plot
              axis.text.y = element_blank(),
              axis.text.x = element_text(size = 7),
              legend.title = element_text(size = 7,
                                          face = "bold")) +
        labs(title = data$sample[1],
             y = "NES",
             x = "") +
        theme(plot.title = element_text(hjust = 0.5)) +
        ylim(-6, 6) +
        scale_color_gradient(low = plot_cols[2],
                             high =plot_cols[1])

    return(plot_name)
}



top5up_down <- rbind(gsea_output %>%
                        slice_head(n = 5),
                    gsea_output %>%
                        slice_head(n = 5)) %>%
                    dplyr::select(pathway,
                                    NES,
                                    size,
                                    padj) %>%
                    arrange(desc(NES)) %>%
                    mutate(pathway = as.factor(pathway) %>%
                                        str_replace_all("_", " ") %>%
                                        str_wrap(65) %>%
                                        fct_reorder(NES),
                       sample = "post_chemo_prim",
                       order = seq_len(n()),
                       justify_y = if_else(NES > 0, 1, 0),
                       y_pos = if_else(NES > 0, -0.1, 0.1))
gsea_plot <- two_way_dotplot(top5up_down, x_col = "NES")



```               



```{r}
human_sobj <- qs::qread("output/seurat_objects/comb_sobjs/human.qs")
mouse_sobj <- qs::qread("output/seurat_objects/comb_sobjs/mouse.qs")

DimPlot(human_sobj,
        group.by = c("time_point", "sample_name"),
        label = TRUE,
        cols = c(plot_cols, sample(rainbow(1000))),
        shuffle = TRUE)

x <- DimPlot(object = human_sobj,
        #label = TRUE,
        group.by = "time_point",
        cols = c(plot_cols, sample(rainbow(1000))),
        shuffle = TRUE,
        label.size = 4) +
        ggtitle("Figure 2. Clustering of OS cells pre- and post-chemotherapy") +
        theme(plot.title = element_text(size = 6,
                                        hjust = 0.5),
              legend.position = "top") +
        #NoLegend() +
        coord_fixed()

FeaturePlot(human_sobj, features = c("COL1A1", "COL1A2", "SATB2", "COL3A1"))
Idents(human_sobj) <- human_sobj$time_point

degs_result <- FindMarkers(human_sobj,
                        ident.1 = "post_treatment",
                        ident.2 = "pre_treatment")

degs_result <- degs_result %>%
    arrange(desc(avg_log2FC))

gene_list <- degs_result %>%
    head(10) %>%
    rownames()

DotPlot(human_sobj, features = gene_list, group.by = "time_point", scale = T)

VlnPlot(human_sobj, features = gene_list, group.by = "time_point")

gsea_input <- as.vector(degs_result$avg_log2FC)

names(gsea_input) <- rownames(degs_result)

gsea_ref <- msigdbr::msigdbr(species = "human",
                             category = "H") %>%
    split(x = .$gene_symbol, f = .$gs_name)

gsea_output <- fgsea::fgseaMultilevel(gsea_ref,
                                         gsea_input,
                                         minSize = 10,
                                         maxSize = 500,
                                         nPerm = 1000)

gsea_output <- gsea_output %>%
            dplyr::arrange(desc(NES)) %>%
            filter(padj < 0.05) %>% 
            mutate(pathway = stringr::str_replace_all(pathway, "_", " "))


two_way_dotplot <- function(data, x_col = "z_score") {
    lab4plot <-
        tibble(y = c(-2.5, 2.5),
               x = c(0.2, 0.2),
               label = c("Downregulated", "Upregulated"))

    plot_name <-
        ggplot() +
        geom_point(data = data,
                 aes(x = -1 * order,
                     y = get(x_col),
                     color = -log10(padj),
                     size = size),
                 stat = "identity",
                 alpha = 0.8) +
        coord_flip() +
        # geom_hline(yintercept = 0,
        #             color = "black",
        #             linewidth = 0.5) +
        geom_text(data = data,                #text for pathways names
                    aes(x = -1 * order,
                        y = get(x_col) + (y_pos *5),
                        hjust = justify_y,
                        label = pathway),
                        size = 2,
                        fontface = "bold") +
        geom_text(data = lab4plot,    #text for upregulated/downregulated
                  aes(x = x,
                      y = y,
                      label = label),
                  fontface = "bold",
                  size = 2.5) +
        scale_fill_manual(values = plot_cols,
                          name = paste0(x_col, " > 0")) +
        theme(strip.background = element_rect(color = "white",
                                              fill = "white"),
              #legend.position = "none",
              panel.grid.major = element_blank(),
              panel.grid.minor = element_blank(),
              panel.border = element_blank(),
              axis.line.x = element_line(color = "black"),
              axis.line.y = element_blank(),
              axis.title.x = element_text(size = 7),
              axis.ticks.y = element_blank(),
              plot.title = element_text(size = 7, face = "bold"),    #title of the plot
              axis.text.y = element_blank(),
              axis.text.x = element_text(size = 7),
              legend.title = element_text(size = 7,
                                          face = "bold")) +
        labs(title = data$sample[1],
             y = "NES",
             x = "") +
        theme(plot.title = element_text(hjust = 0.5)) +
        ylim(-6, 6) +
        scale_color_gradient(low = plot_cols[2],
                             high =plot_cols[1])

    return(plot_name)
}


top5up_down <- rbind(gsea_output %>%
                        slice_head(n = 8),
                    gsea_output %>%
                        slice_tail(n = 4)) %>%
                    dplyr::select(pathway,
                                    NES,
                                    size,
                                    padj) %>%
                    arrange(desc(NES)) %>%
                    mutate(pathway = as.factor(pathway) %>%
                                        str_replace_all("_", " ") %>%
                                        str_wrap(65) %>%
                                        fct_reorder(NES),
                       sample = "post_chemo_prim",
                       order = seq_len(n()),
                       justify_y = if_else(NES > 0, 1, 0),
                       y_pos = if_else(NES > 0, -0.1, 0.1))
gsea_plot <- two_way_dotplot(top5up_down, x_col = "NES")

ggsave("output/plots/gsea_plot.jpg",
        width = 6,
        height = 5,
        plot = gsea_plot)


mouse <- DimPlot(mouse_sobj, group.by = "time_point")




patchwork::wrap_plot(human, mouse)

x <- human+mouse

DimPlot(human_sobj, group.by = "time_point", )

DimPlot(sobj, group.by = c("sample_name", "seurat_clusters", "time_point"))

DotPlot(sobj, features = c("FOXM1", "MCL1", "FGF18", "FGF2" , "DTYMK", "HIF1A"), group.by = "time_point", scale = F)

DotPlot(sobj, features = c("HIF1A", "VEGFA" , "IGFBP5", "NDRG1", "FAM162A", "PGK1", "ANGPTL4"), group.by = "time_point", scale = F)

DotPlot(sobj, features = "HIF1A", group.by = "time_point", scale = F)

FeaturePlot(sobj, features = stem_cell)

cancer_features <- c("COL1A1", "COL1A2", "SATB2", "COL3A1")

fibroblast_markers <- c("LOXL1", "LUM", "COL5A1", "FBLN1", "FBLN2")

james_marker <- c("KRT8", "KRT19")

stem_cell <- c("PCNA", "MCM2", "MKI67", "PLK1")

quiscent_markers <- c("CDC2", "CCNB1", "CCNB2", "CCNG1", "CHK1", "BUB3", "STK6", "SKB1", "CSE1L")

kill_cc(sobj)

list <- degs_result %>% slice_head(n=10) %>% select(gene) %>% as.data.frame

list <- c("FOXM1", "POSTN", "MCL1", "PTBP1", "MYC", "AKT", "VEDGA")

#PTBP1 binds to mcl1

DotPlot(sobj, features = lists, group.by = "time_point", scale=F)

lists <- c("DTYMK", "MDK", "ISG15", "BST2", "CALD1", "H2AFZ", "POSTN")

# objects <- SplitObject(sobj, split.by = "time_point")

# objects$post_chemo_prim <-
#     RunHarmony(objects$post_chemo_prim, group.by.vars = "sample_name")

# objects$post_chemo_prim <- objects$post_chemo_prim %>%
#     process_seurat(reduction = "harmony")

# merged <- merge(objects[[1]],
#                 objects[2:length(objects)],
#                 add.cell.id = names(objects),
#                 project = "merged")

optimize_silhouette(sobj,
                    test_res = seq(0.1, 1, by = 0.1))

sobj <- sobj %>% process_seurat(resolution = 0.1)


Idents(human_sobj) <- human_sobj$time_point
umap <- 
    DimPlot(object = human_sobj,
    label = TRUE,
    cols = c(plot_cols, sample(rainbow(1000))),
    shuffle = TRUE) +
    ggtitle("Figure 3. Clustering of OS cells pre- and post-chemotherapy") +
    theme(plot.title = element_text(size = 7))
            cols = c("pre_chemo_prim"="#E68613", "post_chemo_prim" = "#ABA300") 
            labs(title = "Pre- and post-chemo clusters") +
            theme(plot.title = element_text(hjust = 0.5))

ggsave("output/plots/umap.jpg",
        width = 4,
        height = 3,
        plot = umap)

sobj <- human_sobj

Idents(sobj) <- sobj$time_point

post_chemo <- FindMarkers(sobj,
                        ident.1 = "post_treatment",
                        ident.2 = "pre_treatment")


post_chemo <- post_chemo %>%
    arrange(desc(avg_log2FC))

gsea_input <- as.vector(post_chemo$avg_log2FC)
names(gsea_input) <- rownames(post_chemo)



gsea_ref <- msigdbr::msigdbr(species = "Homo sapiens",
                             category = "C5",
                             subcategory = "BP") %>%
    split(x = .$gene_symbol, f = .$gs_name)

gsea_output <- fgsea::fgseaMultilevel(gsea_ref,
                                         gsea_input,
                                         minSize = 10,
                                         maxSize = 500,
                                         nPerm = 1000)

gsea_output <- gsea_output %>%
            dplyr::arrange(desc(NES)) %>%
            filter(padj < 0.05) %>% 
            mutate(pathway = stringr::str_replace_all(pathway, "_", " "))

top5up_down <- rbind(gsea_output %>%
                        slice_head(n = 5),
                        gsea_output %>%
                        filter(NES < 0) %>%
                        slice_tail(n = 5)) %>%
                        dplyr::select(pathway,
                                    NES,
                                    size,
                                    padj) %>%
                    arrange(desc(NES)) %>%
                    mutate(pathway = as.factor(pathway) %>%
                            str_wrap(80) %>%
                            fct_reorder(NES),
                       sample = "post_chemo_prim",
                       order = 1:n(),
                       justify_y = if_else(NES > 0, 1, 0),
                       y_pos = if_else(NES > 0, -0.1, 0.1))


x <- print(two_way_plot(top5up_down, x_col = "NES"))
ggsave("output/plots/x.jpg",
        width = 4,
        height = 3,
        plot = x)



```



## GSEA
```{r}

##matts way
calc_logfc <- function(sobj,
                       group_var,
                       group_1,
                       group_2,
                       epsilon = 1,
                       assay = "SCT") {
    all_obs_exp <-
        AverageExpression(sobj,
                          group.by = group_var,
                          assays = assay)[[1]] %>%
        as.data.frame()

    log_fc <-
        tibble(log_fc = log2((all_obs_exp[[group_1]] + epsilon) /
                             (all_obs_exp[[group_2]] + epsilon)),
               gene = rownames(all_obs_exp))

    return(log_fc)
}

post_chemo <-
       calc_logfc(sobj,
                  group_var = "time_point",
                  group_1 = "post_treatment",
                  group_2 = "pre_treatment",
                  epsilon = 1,
                  assay = "RNA")


degs_result <- post_chemo %>%
    arrange(desc(log_fc))


gsea_input <- as.vector(degs_result$log_fc)
names(gsea_input) <- degs_result$gene


# ont <- tribble(
#   ~code, ~name,
#   "BP", "GO BioProcesses",
#   "MF", "GO MolFunction",
#   "CC", "GO CellComponent"
# )

gsea_ref <- msigdbr::msigdbr(species = "Homo sapiens",
                             category = "C5",
                             subcategory = "GO:MF") %>%
    split(x = .$gene_symbol, f = .$gs_name)

gsea_ref <- msigdbr::msigdbr(species = "Homo sapiens",
                             category = "C8") %>%
    split(x = .$gene_symbol, f = .$gs_name)

gsea_output <- fgsea::fgseaMultilevel(gsea_ref,
                                         gsea_input,
                                         minSize = 10,
                                         maxSize = 500,
                                         nPerm = 1000)

gsea_output <- gsea_output %>%
            dplyr::arrange(desc(NES)) %>%
            filter(padj < 0.05) %>% 
            mutate(pathway = stringr::str_replace_all(pathway, "_", " "))

top5up_down <- rbind(gsea_output %>%
                        slice_head(n = 5),
                        gsea_output %>%
                        filter(NES < 0) %>%
                        slice_tail(n = 5)) %>%
                        dplyr::select(pathway,
                                    NES,
                                    size,
                                    padj) %>%
                    arrange(desc(NES)) %>%
                    mutate(pathway = as.factor(pathway) %>%
                            str_wrap(80) %>%
                            fct_reorder(NES),
                       sample = "post_chemo_prim",
                       order = 1:n(),
                       justify_y = if_else(NES > 0, 1, 0),
                       y_pos = if_else(NES > 0, -0.1, 0.1))


x <- print(two_way_plot(top5up_down, x_col = "NES"))
ggsave("output/plots/x.jpg",
        width = 4,
        height = 3,
        plot = x)




two_way_plot <- function(data, x_col = "z_score") {
    lab4plot <-
        tibble(y = c(-3, 3),
               x = c(0.2, 0.2),
               label = c("Downregulated", "Upregulated"))

    plot_name <-
        ggplot() +
        geom_bar(data = data,
                 aes(x = -1 * order,
                     y = get(x_col),
                     fill = get(x_col) > 0),
                 stat = "identity",
                 alpha = 0.8) +
        coord_flip() +
        geom_hline(yintercept = 0,
                    color = "black",
                    linewidth = 0.5) +
        geom_text(data = data,
                    aes(x = -1 * order,
                        y = y_pos,
                        hjust = justify_y,
                        label = pathway),
                    size = 1) +
        geom_text(data = lab4plot,
                  aes(x = x,
                      y = y,
                      label = label),
                  fontface = "bold",
                  size = 2) +
        scale_fill_manual(values = plot_cols,
                          name = paste0(x_col, " > 0")) +
        theme(strip.background = element_rect(color = "white",
                                              fill = "white"),
              legend.position = "none",
              panel.grid.major = element_blank(),
              panel.grid.minor = element_blank(),
              panel.border = element_blank(),
              axis.line.x = element_line(color = "black"),
              axis.line.y = element_blank(),
              axis.title.x = element_text(size = 7),
              axis.ticks.y = element_blank(),
              plot.title = element_text(size = 10, face = "bold"),
              axis.text.y = element_blank(),
              axis.text.x = element_text(size = 7)) +
        labs(title = data$sample[1],
             y = "NES",
             x = "") +
        theme(plot.title = element_text(hjust = 0.5)) +
        ylim(-6, 6)

    return(plot_name)
}




```