---
title: "Just practice"
author: "Yogesh"
date: "2020-07-01"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Introduction
```{r, echo=FALSE}
library(ggplot2)
library(dplyr)
library(tidyr)
```

```{r, echo=FALSE}
ravis_data <- openxlsx::read.xlsx(xlsxFile = "Annexure_2_Fold_change.xlsx",
                                  sheet = 3)

head(ravis_data)
unique(ravis_data$Name)

ravis_data_formatted <- 
  pivot_longer(ravis_data,
                          cols = c(-S_No,
                                  -LabNo,
                                  -Tx_No,
                                  -Name,
                                  -Age,
                                  -Sex,
                                  -Group,
                                  -CRNo), 
                           names_to = "stuff",
                           values_to = "Expression") %>%
    separate("stuff", sep = "_", into = c("gene", "timepoint")) %>%
	mutate(Expression = round(Expression, 5)) %>%
    mutate(name_age_timepoint = paste(S_No, Name, Age, timepoint, sep = "_")) %>%
    select(-Name, -timepoint, -Tx_No, -S_No, -CRNo, -LabNo, -Age, -Sex, -Group) %>%
    tidyr::pivot_wider(names_from = name_age_timepoint,
                       values_from = Expression,
					   	values_fill = 0)

# PCA analysis
run_pca <- ravis_data_formatted %>%
    select(gene, matches("Post")) %>% 
	arrange(gene) %>%
    tibble::column_to_rownames(var = "gene") %>%
	t() %>%
    prcomp(center = TRUE, scale = TRUE)

# append the run_pca$x to the ravis_data_formatted
ravis_data_metadata <- ravis_data_formatted %>%
	tibble::column_to_rownames(var = "gene")


pca_result <- cbind(ravis_data_formatted, run_pca$x)

# visualize the PCA result
ggplot(data = as.data.frame(run_pca$x), aes(x = PC1, y = PC2)) +
	geom_point() +
	theme_minimal() +
	geom_text(aes(label = rownames(run_pca$x)), hjust = 0, vjust = 0) +	
	ggrepel::geom_text_repel(aes(label = rownames(run_pca$x)), hjust = 0, vjust = 0) +
	labs(title = "PCA plot")


ggplot(data = as.data.frame(run_pca$x), aes(x = PC1, y = PC2)) +
	geom_point() +
	geom_text(aes(label = rownames(run_pca$x)), hjust = 0, vjust = 0) +
	theme_minimal() +
	labs(title = "PCA plot")



# perform clustering using PCA
clustering_result <- kmeans(pca_result$x[, 1:2], centers = 4)

# Add cluster labels to gene_info
gene_info$cluster <- clustering_result$cluster
gene_info$age <- ravis_data$Age
gene_info$gender <- ravis_data$Sex
gene_info$group <- ravis_data$Group
# visualize the PCA result
ggplot(data = as.data.frame(pca_result$x), aes(x = PC1, y = PC2)) +
  geom_point(aes(color = as.factor(gene_info$cluster))) +
  theme_minimal() +
    labs(title = "PCA plot with cluster labels")

# add rownames label to each dot in ggplot
ggplot(data = as.data.frame(pca_result$x), aes(x = PC1, y = PC2)) +
    geom_point(aes(color = as.factor(gene_info$cluster))) +
    geom_text(aes(label = rownames(gene_info)), hjust = 0, vjust = 0) +
    theme_minimal() +
    labs(title = "PCA plot with cluster labels")

ggplot(data = as.data.frame(pca_result$x), aes(x = PC1, y = PC2)) +
    geom_point(aes(color = as.factor(gene_info$cluster))) +
    geom_text(aes(label = gene_info$age), hjust = 0, vjust = 0) +
    theme_minimal() +
    labs(title = "PCA plot with cluster labels")

# repel the labels in PC plots
ggplot(data = as.data.frame(pca_result$x), aes(x = PC1, y = PC2)) +
    geom_point(aes(color = gene_info$group)) +
    ggrepel::geom_text_repel(aes(label = gene_info$group), hjust = 0, vjust = 0) +
    theme_minimal() +
    labs(title = "PCA plot with cluster labels")





```

# clustering 
```{r, echo=FALSE}

billboard
billboard %>%
  pivot_longer(
    cols = starts_with("wk"),
    names_to = "week",
    names_prefix = "wk",
    values_to = "rank",
    values_drop_na = TRUE
  )



```